<?php
$issuers = $this->getIssuers();

if (sizeof($issuers) > 0) {
	$options = array_reduce( array_keys( $issuers ), function ( $res, $issuer ) use ( $issuers ) {
		return $res . '<option value="' . $issuer . '">' . $issuers[ $issuer ] . '</option>';
	}, '<option value="">' . $this->__( 'Select your bank' ) . '</option>' );

	?>
    <div class="form-list" id="payment_form_nocks_ideal" style="display:none">
        <div class="input-box">
            <select name="nocks_ideal_issuer" id="nocks_ideal_issuer" class="input-text">
                <?php echo $options; ?>
            </select>
         </div>
    </div>
    <script type="text/javascript">
        var nocksIdealIssuerSelect = document.getElementById('nocks_ideal_issuer');
        var button = document.getElementById('payment-buttons-container').getElementsByTagName('button')[0];

        var checkDisable = function() {
            button.disabled = document.querySelector('input[name="payment[method]"]:checked').value === 'nocks_ideal' && nocksIdealIssuerSelect.value === '';
        };

        var input = document.querySelectorAll('input[name="payment[method]"]').forEach((inputElement) => {
            inputElement.onchange = checkDisable;
        })

        nocksIdealIssuerSelect.onchange = checkDisable;

        checkDisable();
    </script>
	<?php
}
